export { default as HomeTemplate } from "./HomeTemplate"
export { default as TestimonialsTemplate } from "./TestimonialsTemplate"
export { default as AboutTemplate } from "./AboutTemplate"
export { default as ContactTemplate } from "./ContactTemplate"
export { default as HealthInsuranceTemplate } from "./HealthInsuranceTemplate"
