export { default as Header } from "./Header"
export { default as Footer } from "./Footer"
export { default as Banner } from "./Banner"
export { default as HomeSection } from "./HomeSection"
export { default as HomeInsuranceCompanies } from "./HomeInsuranceCompanies"
export { default as HomeClients } from "./HomeClients"
